import 'package:KPPL/styles.dart';
import 'package:flutter/material.dart';

class TermsAndConditions extends StatelessWidget {
  @override
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: MyColors.backgroundNewPage,
      body: Scrollbar(
        child: SingleChildScrollView(
          child: Container(
            padding: EdgeInsets.all(8),
            child: Column(
              children: [
                Center(
                    child: Text(
                  "Terms and Conditions",
                  style: TextStyle(
                      color: MyColors.primaryNew,
                      fontSize: 18,
                      fontWeight: FontWeight.w700),
                )),
                Text(
                  '''This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under, as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of www.katariaplastics.com 
Welcome to Kataria Plastics Pvt. Ltd., India ("Company”) website www.katariaplasticss.com  (“Website”) Terms and Conditions of Use. Kataria Plastics Pvt. Ltd, India operates this Website as a service. By using this Website owned, operated or maintained by Kataria Plastics Pvt. Ltd, India or its affiliates, you, the user, are deemed to have agreed to comply with and be bound by the following terms and conditions of use (the “Terms”) and is a legally binding agreement between you and Kataria Plastics Pvt. Ltd., India . These Terms govern your use of the Website, Materials, Your Content and the services offered through Website. For the purpose of these Terms, wherever the context so requires “you” or “your” or “user” shall mean any natural or legal person who has agreed to become a member of the Website by registering on the Website as a registered user or browses the Website.
''',
                  textAlign: TextAlign.justify,
                ),
                Text(
                  "COMPANY INFORMATION",
                  style: TextStyle(fontWeight: FontWeight.w700),
                ),
                Text(
                  '''This page sets forth the Terms and Conditions under which (i) Owner i.e. Kataria Plastics Private Limited provides the information on this Website, as well as the terms and conditions governing your use of this site; and (ii) the terms and conditions for use of our Services.
Kataria Plastics Private Limited is a Private incorporated on 21 March 1996. It is classified as Non-govt company and is registered at Registrar of Companies, Gwalior. Its authorized share capital is Rs. 18,712,480 and its paid up capital is Rs. 18,687,480. It is inolved in Manufacture of plastic products
Kataria Plastics Private Limited's Annual General Meeting (AGM) was last held on 30 September 2019 and as per records from Ministry of Corporate Affairs (MCA), its balance sheet was last filed on 31 March 2019.
Directors of Kataria Plastics Private Limited are Suyash Kataria, Hemant Kataria, .
Kataria Plastics Private Limited's Corporate Identification Number is (CIN) U25203MP1996PTC010637 and its registration number is 10637.Its Email address is katariaplastics@rediffmail.com and its registered address is 39-43, 44A INDUSTRIAL ESTATE AREA RATLAM Ratlam MP 457001 IN , - , .
''',
                  textAlign: TextAlign.justify,
                ),
                Text(
                  "CONSENT TO ELECTRONIC COMMUNICATIONS AND TRANSACTIONS",
                  style: TextStyle(fontWeight: FontWeight.w700),
                ),
                Text(
                  '''By clicking the ‘I Agree’ button, you consent to conduct transactions and receive communications, notices and information from us electronically, whether sent by e-mail or other electronic means. Electronic communications shall be deemed to have been received by you when we send the electronic communication to the email address / mobile number that as per our records, or when we post the electronic communication on the Application or the Website.''',
                  textAlign: TextAlign.justify,
                ),
                Text(
                  "USER REGISTRATION",
                  style: TextStyle(fontWeight: FontWeight.w700),
                ),
                Text(
                  '''You may use the Website without registration however, to participate in certain activities of the Website you may be requested to create an account or you can login any other third party service account permitted by the Websites.  In the event you wish to create an account with us you may do so by completing the registration process. You agree to 
a) provide true, accurate, correct and complete information as prompted by the applicable registration form 
b) maintain and update true, accurate, correct and complete information provided by you during the registration process. 
You may be required to choose a password and user name. You are solely responsible for maintaining the confidentiality of your password and account.
If at any time Company believes that your account and password is being misused in any manner, or that the information provided by you during the registration process is not true, inaccurate or incomplete the Company reserves the right to cancel your account and block your access to Website.
You are entirely responsible for any and all activities that occur under your account. You agree to notify the Company of any unauthorized use of your account or any breach of security. Company will not be liable for any loss that you may incur as a result of someone else using your password or account or your failure to comply with this section.
''',
                  textAlign: TextAlign.justify,
                ),
                Text(
                  "TERMS OF USE OF THE WEBSITE",
                  style: TextStyle(fontWeight: FontWeight.w700),
                ),
                Text(
                  '''All materials herein are proprietary to Company and protected by worldwide copyright and other intellectual property laws. Except as stated herein, none of the Materials may be modified, copied, reproduced, distributed, republished, downloaded, displayed, sold, compiled, posted or transmitted in any form or by any means, including but not limited to, electronic, mechanical, photocopying, recording or other means, without the prior express written permission of the Company.
Company hereby grants you the right to access and use the Website only for your personal and non-commercial use. You may not use the Website for commercial purposes or in any way that is unlawful, or harms us or any other person or entity, as determined in our sole discretion.
You may post/share links/images/text content on the Website on social platforms like Facebook, Twitter, Google+, Pinterest, with appropriate link back to the original source.
When the Website provides for the download of particular Material including a software, you may download such Material or software to a computer or mobile device (as applicable) for your personal, non-commercial use only, provided that you (a) keep intact all copyright and other proprietary notices, (b) make no modification to, and do not rent, lease, loan, sell, distribute, copy(except to create a single copy for your own backup purposes), or create any derivative works based on the Website or the Material including the software, in whole or in part, and (c) transfer any Material or software or any part thereof to any other computer or mobile device. Any commercial or business use of the Website or any Material including the Software is expressly prohibited.
Except as expressly provided above, nothing contained herein shall be construed as conferring, by implication, estopped or otherwise, any license or right under any patent, trademark or copyright of the Company.
You acknowledge and agree that nothing in these Terms shall have the effect of transferring the ownership of any copyrights, trademarks, service marks, trade names or other proprietary rights in the Website or Material or any part thereof to you or any third party.
We reserve the right, and you authorize us, to use and freely assign all information regarding the use of this Website by you and all information provided by you in any manner consistent with our Privacy Policy.
Taxes, Duties and Licenses. Buyer agrees to pay any and all applicable federal, state and local taxes (domestic and foreign) to which the Goods may be subject, including, without limitation, excise taxes, sales taxes, property tax, value-added taxes and use taxes, duties and license fees
''',
                  textAlign: TextAlign.justify,
                ),
                Text(
                  "USE OF GOOGLE ANALYTICS",
                  style: TextStyle(fontWeight: FontWeight.w700),
                ),
                Text(
                  '''The Site uses Google Analytics, a web and mobile analytics service provided by Google, Inc.(“Google”). Google Analytics uses “cookies”, which are text files placed on your device, to help analyze how users use the Website. Â  The information generated by the cookie about your use of the Website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the Website, compiling reports on Website activity for operators and providing other services relating to Website activity and Internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google’s behalf. By using this Website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.''',
                  textAlign: TextAlign.justify,
                ),
                Text(
                  "LINKED SITES",
                  style: TextStyle(fontWeight: FontWeight.w700),
                ),
                Text(
                  '''Linked sites are not under the control of Kataria Plastics Private Limited, India and Kataria Plastics Private Limited, India is not responsible for the contents of any linked site or any link contained in a linked site. Kataria Plastics Pvt. Ltd, India provides links to you only as a convenience, and the inclusion of any link does not imply endorsement by Kataria Plastics Pvt.  Ltd, India of the site. Company has no control over such third party website or any offsite dealings with such third parties is at your own risk.''',
                  textAlign: TextAlign.justify,
                ),
                Text(
                  "PROHIBITED USE",
                  style: TextStyle(fontWeight: FontWeight.w700),
                ),
                Text(
                  '''As a condition of your use of the Website, you will not use the Website for any purpose that is unlawful or prohibited by these Terms or by any domestic or international laws, statues, ordinances and regulations. Your use of Website is your responsibility. You shall not, display, upload, modify, publish, transmit, update or share any information on the Website, that â€“
Belongs to another person and to which you do not have any right;
Is grossly harmful, harassing, blasphemous, defamatory, obscene, Â pornographic, libelous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner;
Involves the transmission of “junk mail”, ”chain letters”, or unsolicited mass mailing or “spamming” or unsolicited commercial advertisement;
Harm minors in any way;
Infringes any patent, trademark, copyright or other proprietary rights;
Violates any law for the time being in force;
Deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
Impersonate another person;
Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;
''',
                  textAlign: TextAlign.justify,
                ),
                Text(
                  "DISCLAIMER OF WARRANTIES",
                  style: TextStyle(fontWeight: FontWeight.w700),
                ),
                Text(
                  '''KATARIA PLASTICS PRIVATE LIMITED, INDIA MAKES NO REPRESENTATION AS TO THE ACCURACY, TIMELINESS, OR COMPLETENESS OF THE WEBSITE MATERIALS. KATARIA PLASTICS PRIVATE LIMITED, INDIA PERIODICALLY AMENDS, CHANGES, ADDS, DELETES, UPDATES OR ALTERS THE INFORMATION, INCLUDING, WITHOUT LIMITATION, THE TERMS OF USE, AT THE WEBSITE WITHOUT NOTICE. FURTHER, KATARIA PLASTICS PRIVATE LIMITED, INDIA ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY ERRORS OR OMISSIONS IN THE CONTENT OF THE WEBSITE. KATARIA PLASTICS PRIVATE  LIMITED, INDIA SPECIFICALLY DISCLAIMS ANY DUTY TO UPDATE THE INFORMATION ON THE APPLICATION. YOU ARE RESPONSIBLE FOR VERIFYING ALL INFORMATION LOCATED ON THIS APPLICATION.
ALL MATERIALS, INFORMATION, SOFTWARE, PRODUCTS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THIS WEBSITE (THE "CONTENT") ARE PROVIDED "AS IS" AND "AS AVAILABLE" FOR YOUR USE. THE CONTENT IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND TITLE.
''',
                  textAlign: TextAlign.justify,
                ),
                Text(
                  "APPLICABLE LAW",
                  style: TextStyle(fontWeight: FontWeight.w700),
                ),
                Text(
                  '''This Agreement shall be governed by and interpreted and construed in accordance with the laws of India. Notwithstanding the foregoing, we reserve the right to pursue any action or claim against you in any court of competent jurisdiction which we believe is the most appropriate to seek any relief. Subject to the arbitration provision herein, the courts at <RATLAM>, India shall have exclusive jurisdiction over any claims or matters arising out of these Terms and Conditions.''',
                  textAlign: TextAlign.justify,
                ),
                Text(
                  "CHANGES TO TERMS OF USE",
                  style: TextStyle(fontWeight: FontWeight.w700),
                ),
                Text(
                  '''Kataria Plastics Pvt. Ltd, India reserves the right to modify them at any time, and without actual notice to you. All such changes to these Terms will appear on the Website.
By using this Website following any modifications to the Terms, you agree to be bound by any such modifications to the Terms. Our current privacy policy, which addresses our use and release of information collected from your use of the Website and receipt of the Services is available here. If any changes to these terms are unacceptable to you, you must discontinue use of the Website. We reserve the right to suspend or deny, in our sole discretion, your access to all or any portion of the Website, including for any violation of any provision of these Terms. We also reserve the right to change the Website without notice to you, at any time.
''',
                  textAlign: TextAlign.justify,
                ),
                Text(
                  "Contact",
                  style: TextStyle(fontWeight: FontWeight.w700),
                ),
                Text(
                  '''If you have any questions or suggestions regarding our Terms and Conditions, please contact us at Helpdesk@Katariaplastics.com .''',
                  textAlign: TextAlign.justify,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
